### ISSUE TITLE
Не удаётся добавить чайник RK-G212S

### ISSUE THREAD

**Issue by TEMPLATER1** [XNicON/hassio-r4s#1]
Добрый день! Пытаюсь прокинуть свой чайник в HA, но при его добавлении в логах вылезает ошибка, что тип устройства не поддерживается. При этом, после этапа, якобы, сопряжения, который длится секунды 3, HA пишет, что интеграция успешно добавлена, но чайник даже не пищит. Раньше я длительное время использовал интеграцию R4S от "mavrikkk", но после обновления HA до версии 2022.7 (сейчас использую 2022.7.5) она перестала работать. А этот форк не удаётся настроить :(

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ready4sky/__init__.py", line 62, in async_setup_entry
    await kettler.setNameAndType()
  File "/config/custom_components/ready4sky/__init__.py", line 156, in setNameAndType
    await self._conn.setNameAndType()
  File "/config/custom_components/ready4sky/btle.py", line 39, in setNameAndType
    raise BleakError('type device not supported')
bleak.exc.BleakError: type device not supported

![image](https://user-images.githubusercontent.com/40922712/179990779-c39c1533-cbeb-47d3-b172-adff82d12e78.png)

**Comment by XNicON** [comment]
Добрый день, надеюсь Вы нашли уже решение для себя.
Хотелось бы конечно разобраться, т.к. ситуация странная, ведь в списке констант он добавлен.
Можно поподробнее название которое видит bluetooth и версия прошивки (можно через приложение пока посотреть)

**Comment by XNicON** [comment]
@Alex-Matsko спасибо за наблюдение, добавил RFS-KKL002, RFS-KKL003, RFS-KKL004, нашёл по ним информацию, что действительно такие бывают.
А вот версию прошивки не сможете подсказать, какая у Вашего чайника?

**Comment by Alex-Matsko** [comment]
Версия ПО электрочайника: 2.59
Версия Home Assistant: 2022.10.5
