### ISSUE TITLE
CkyCooker M92S

### ISSUE THREAD

**Issue by dead36900** [XNicON/hassio-r4s#14]
Hello! My SkyCooker RMC-M92S is indicated that it is not supported in the list of devices. Please tell me where to go? And how to solve the problem?
![image](https://github.com/XNicON/hassio-r4s/assets/163623766/777be4f6-21d4-416e-9f6b-02d8fb7e8871)
Thank you!

**Comment by dead36900** [comment]
Я думал вы на английском общаетесь. Поэтому извините. Не знаю что делать, ваша интеграция единственная которая по описанию мне подойдёт для мультиварки.

**Comment by XNicON** [comment]
Здравствуйте, попробуйте самостоятельно добавить в файле https://github.com/XNicON/hassio-r4s/blob/master/custom_components/ready4sky/r4sconst.py по аналогии с другими и перезапустить ha. Начнёт обозначаться поддерживаемым в списке.

Потом попробуйте поправлять, если будет реагировать на команды, то я добавлю в список уже для всех.

Там в списке в файле поищите похожую примерно на вашу модель, сейчас не могу сам посмотреть

**Comment by XNicON** [comment]
Хотя странно на скриншоте нет названия модели, только адрес, так не должно быть

**Comment by dead36900** [comment]
Спасибо, она подцепилась, но теперь другая ошибка не удалось настроить.
![image](https://github.com/XNicON/hassio-r4s/assets/163623766/414da739-d4cf-4787-9020-d68e35b7d59c)

**Comment by XNicON** [comment]
Если готовы продолжить, то, включаем логи (на главной, раздел Debug log enable)

и перезагружаем потом в папке ha ищем лог файл и загрузите сюда (весь, не картинкой пжлст)

**Comment by XNicON** [comment]
У меня лог здесь лежит /usr/share/hassio/homeassistant/home-assistant.log

**Comment by dead36900** [comment]
Спасибо! Я перезагрузил HA + отдельно плагин, у меня все заработало. А вопрос такой, мультиварка работает как чайник? Т.е. Я не могу выбрать программу градусы, время и т.д.? Или у меня индивидуальная какая то ситуация, показывает всего 3 датчика. 
![image](https://github.com/XNicON/hassio-r4s/assets/163623766/35faf6bf-4a20-48c5-9c57-305fab56d90b)

![image](https://github.com/XNicON/hassio-r4s/assets/163623766/f87a201c-6b4a-441d-9e60-99ea6b1b2e9a)

**Comment by XNicON** [comment]
Можете тогда сказать, что добавили в файл?

По скриншотам вижу, что определилось корректно, но честно мультиварки нет, я не в курсе как она работает, но там внутри cooker должны быть доступные режимы.

и к сожалению в HA нет нормального типа устройства как мультиварка, а в принципе подробно с выставлением режимов, некому организовать максимально удобно в интерфейсе, что есть, то есть

**Comment by dead36900** [comment]
Да, я просто скопировал все что вы скидывали из той ссылки, и заработало.
