### ISSUE TITLE
Не работает мульиварка RMC-M92S

### ISSUE THREAD

**Issue by firmfreez** [XNicON/hassio-r4s#15]
<img width="1191" alt="image" src="https://github.com/user-attachments/assets/11520f01-4c66-4c97-8c78-9ca2a0f6919f">

В чем может быть причина?

**Comment by XNicON** [comment]
Что-то типа лимит **активных** соединений ичсерпан, слишком много у вас на блютузе соединений

**Comment by firmfreez** [comment]
У меня блютус встроенный в Raspberry Pi, и стоит HA OS. По блютус еще ни одного устройства не подключал

**Comment by XNicON** [comment]
а компонент вообще вклюлён в HA ? в интеграциях

**Comment by firmfreez** [comment]
![image](https://github.com/user-attachments/assets/07e79223-456c-4101-8b5d-a828417de4c9)
Proxy не настраивал.
Чистая новая HA, поставил вчера, успел только HACS поставить и zigee2mqtt

**Comment by XNicON** [comment]
Попробуйте поближе поставить мультиварку при первом соединении, кому-то помогло именно такое. 

К сожалению, если bleak (базовый пакет BT для HA) не может установить соединение с устройством, я ничего не могу сделать

**Comment by firmfreez** [comment]
Спасибо! В общем поднес ближе и получилось 👍
Мультиварка добавилась и есть управление.

Но есть нюанс, как только ставлю ее на место на кухне (после успешного подключения) - перестает реагировать на команды и при перезапуске опять та же ошибка.

Скажите пожалуйста: можно ли как то решить эту проблему с радиусом сигнала? (программно или аппаратно)
Очень странно, что ловит только на коротком расстоянии, хотя те же блютус датчики температуры в разы дальше находятся и прекрасно ловятся

**Comment by XNicON** [comment]
Честно не понятно из-за чего такое, возможно блютуз антенна сбовата и у расбери и у мультиварки, в итоге оба не дотягиваются, и у расбери вроде нет разъёма для внешней антенны.
Тут наверное стоит обратить внимание на уже упомянутую технологию Bluetooth Proxy в HA, правда я сам не пробовал, и не понимаю, подойдёт ли она здесь или нет.

Самый простой разместить умный сервер на территории мультиварки всё же 😉
