### ISSUE TITLE
Ошибка настройки интеграции

### ISSUE THREAD

**Issue by NikDevx** [XNicON/hassio-r4s#2]
Homeassistant - 2022.7.7
Получаю ошибку при попытке добавить интеграцию - _Не удалось загрузить мастер настройки: undefined_
В чем может быть проблема?

**Comment by XNicON** [comment]
Без понятия, какая-то ваша локальная проблема.
может помочь логи посмотреть.
чтобы узнать как их включить, в реадми посмотрите пункт Debug log enable
