### ISSUE TITLE
(WARNING) Detected integration that attempted to call BleakClient with an address instead of a BLEDevice.

### ISSUE THREAD

**Issue by Sensei8** [XNicON/hassio-r4s#4]
Судя по документации, советуют везде использовать BLEDevice, поменял в btle.py на 53 строке на
```
                device = await BleakScanner.find_device_by_address(self._mac, adapter=self._adapter)
                self._conn = BleakClient(device)
```
соединение стало постабильнее, чайник быстрее отзывается на команды.

**Comment by XNicON** [comment]
Да, недавно только это стало возможно, в планах переделать на использования их наработок

**Comment by XNicON** [comment]
Это оказалось проще чем я думал. В мастере
