### ISSUE TITLE
Некорректная работа подогрева через Yandex Smart Home

### ISSUE THREAD

**Issue by sashayohan** [XNicON/hassio-r4s#6]
При добавлении чайника через Yandex Smart Home неправильно отрабатывает голосовые команды.
Команды Поставь или Вскипяти чайник работают корректно, там он до 100 градусов кипятит.
Но, например, если сказать Нагрей или Подогрей чайник, то он не включается, меняется только температура (прибавляется один градус, до какой нужно поддерживать)

**Comment by XNicON** [comment]
Всего на 1 градус говорите? Не на 5 - точно?

**Comment by sashayohan** [comment]
да, прибавляет один градус к атрибуту temperature

**Comment by XNicON** [comment]
О, это отлично, тогда сейчас сделаю, чтобы работало

**Comment by XNicON** [comment]
Правки внес, должно теперь работать

**Comment by sashayohan** [comment]
Спасибо! Обновился, сейчас хорошо срабатывает
